

.PHONY: all
all:

include module.mk

ROOT := ../

all: 
	$(MAKE) --directory=$(ROOT) all
#	$(MAKE) --directory=$(ROOT) cspcpp_test

.PHONY: clean
clean:
	$(MAKE) --directory=$(ROOT) clean
	$(RM) *_temp.log




