##
##
## A Makefile cspcpp_test for compiling ATS programs
##
##

######

#==================================

CWD=$(shell pwd)

MV  := mv -f
RM  := rm -f
SED := sed


#==================================

ATSUSRQ="$(ATSHOME)"
ATSLIBQ=$(ATSUSRQ)
ifeq ($(ATSUSRQ),"")
ATSUSRQ="/usr"
endif # end of [ifeq]

ATSRUNTIME=$(ATSUSRQ)/ccomp/runtime

######

ATSCC=$(ATSUSRQ)/bin/atscc
ATSOPT=$(ATSUSRQ)/bin/atsopt

ATSCCFLAGS=-IATS $(CWD)/contrib

ATS_CC_INC=-I $(ATSRUNTIME) -I $(ATSUSRQ) -I $(CWD)

define atscname
$(patsubst %.dats,%_dats.c,$(patsubst %.sats,%_sats.c,$1))
endef

#= general macro =================================

#CC=gcc
#CXX=g++

######

# file extension for dependency files
depgcc := depgcc
depats := depats


#= general functions =================================
# $(call source-to-object, source-file-list)
source-to-object = $(subst .c,.o,$(filter %.c,$1)) \
                   $(subst .cpp,.o,$(filter %.cpp,$1)) \
                   $(subst .sats,_sats.o,$(filter %.sats,$1)) \
                   $(subst .dats,_dats.o,$(filter %.dats,$1))


# $(subdirectory)
subdirectory = $(patsubst %/module.mk,%,    \
                 $(word                     \
                   $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))

#= functions for building specific target =================================
# ------------------------------------------------------

# ------------------------------------------------------
# $(call make-ec_library, library-name, source-file-list)
define make-ec_library
  ec_lib  += $1
  sources += $2

  $1: $(call source-to-object,$2)
	$(AR) $(ARFLAGS) $$@ $$^
endef

# ------------------------------------------------------
# $(call make-ec_test, program-name, source-file-list)
define make-ec_test
  ec_test += $1
  sources += $2

  $1: $(call source-to-object,$2) $(ec_lib)
	$(CXX) -o $$@ $(call source-to-object,$2) \
          -l$(patsubst lib%.a,%,$(notdir $(ec_lib))) -L$(dir $(ec_lib))
endef
# ------------------------------------------------------
# $(call make-cspcpp_library, library-name, source-file-list)
define make-cspcpp_library
  cspcpp_lib += $1
  sources    += $2

  $1: $(call source-to-object,$2)
#	cp $(ec_lib) $$@
	$(AR) $(ARFLAGS) $$@ $(call source-to-object,$2)
endef

# ------------------------------------------------------
# $(call make-cspcpp_test, program-name, source-file-list)
define make-cspcpp_test
  cspcpp_test += $1
  sources  += $2

  $1: $(call source-to-object,$2) $(cspcpp_lib) $(ec_lib)
	$(CC) -o $$@ $(call source-to-object,$2) \
          -l$(patsubst lib%.a,%,$(notdir $(cspcpp_lib))) -L$(dir $(cspcpp_lib)) \
          -l$(patsubst lib%.a,%,$(notdir $(ec_lib))) -L$(dir $(ec_lib)) \
          -lstdc++ -pthread
endef

# ------------------------------------------------------
# $(call make-logtool_library, library-name, source-file-list)
define make-logtool_library
  logtool_lib += $1
  sources    += $2

  $1: $(call source-to-object,$2)
	$(AR) $(ARFLAGS) $$@ $(call source-to-object,$2)
endef

# ------------------------------------------------------
# $(call make-cspats_library, library-name, source-file-list)
define make-cspats_library
  cspats_lib += $1
  sources    += $2

  $1: $(call source-to-object,$2)
#	cp $(cspcpp_lib) $$@
	$(AR) $(ARFLAGS) $$@ $(call source-to-object,$2)
endef

# ------------------------------------------------------
# $(call make-cspprogram, program-name, source-file-list)
define make-cspprogram
  programs += $1
  sources  += $2

  $1: $(call source-to-object,$2) $(cspats_lib) $(logtool_lib) $(cspcpp_lib) $(ec_lib)
	$(ATSCC) -o $$@ $$(filter %.o,$$^) \
          -l$(patsubst lib%.a,%,$(notdir $(cspats_lib))) -L$(dir $(cspats_lib)) \
          -l$(patsubst lib%.a,%,$(notdir $(cspcpp_lib))) -L$(dir $(cspcpp_lib)) \
          -l$(patsubst lib%.a,%,$(notdir $(logtool_lib))) -L$(dir $(logtool_lib)) \
          -l$(patsubst lib%.a,%,$(notdir $(ec_lib))) -L$(dir $(ec_lib)) \
          -lstdc++ -pthread
endef

#= projects macro =================================

# Collect information from each module in these four variables.
# Initialize them here as simple variables

modules   := contrib/cspats contrib/logtool contrib/cspats/LIB contrib/cspats/LIB/common test
programs  :=
ec_lib    :=
ec_test   :=
cspcpp_lib:=
cspcpp_test:=
cspats_lib:=
logtool_lib:=
libraries :=
sources   :=

objects      = $(call source-to-object,$(sources))

# sources consist of .cpp, .c, .sats, .dats
cpp_files = $(filter %.cpp,$(sources))
c_files   = $(filter %.c,$(sources))
sats_files= $(filter %.sats,$(sources))
dats_files= $(filter %.dats,$(sources))

# generated by atsopt
sats_c_files = $(call atscname,$(sats_files))
dats_c_files = $(call atscname,$(dats_files))
ats_c_files = $(sats_c_files) $(dats_c_files)

ats_obj_files = $(subst .c,.o,$(ats_c_files))

# dependency files
cxx_dep = $(subst .cpp,.$(depgcc),$(cpp_files))
c_dep   = $(subst .c,.$(depgcc),$(c_files))

sats_c_dep   = $(subst .c,.$(depgcc),$(sats_c_files))
dats_c_dep   = $(subst .c,.$(depgcc),$(dats_c_files))

# dependency files generated by atsopt
sats_dep = $(subst .sats,.$(depats),$(sats_files))
dats_dep = $(subst .dats,.$(depats),$(dats_files))


dependencies = $(sats_dep) $(dats_dep) $(cxx_dep) $(c_dep) $(sats_c_dep) $(dats_c_dep)

# =========================================

include_dirs := $(CWD) contrib/cspats/LIB contrib/cspats/LIB/common
CPPFLAGS  += $(addprefix -I ,$(include_dirs))
CFLAGS    += -O0
CXXFLAGS  += -O0
# vpath %.h $(include_dirs)


all:
# todo include $(addsuffix /module.mk,$(modules))
# todo add more xx.mk here
include contrib/cspats/LIB/common/module.mk
include contrib/cspats/LIB/module.mk
include contrib/cspats/module.mk
include contrib/logtool/module.mk
include test/module.mk

# The following must be after the "include".
libraries += $(ec_lib) $(cspcpp_lib) $(cspats_lib) $(logtool_lib)
lib_test += $(ec_test) $(cspcpp_test)

# =targets ========================================

.PHONY: all
all: $(programs)

.PHONY: libraries
libraries: $(libraries)

.PHONY: ec_lib
ec_lib: $(ec_lib)

.PHONY: ec_test
ec_test: $(ec_test)

.PHONY: cspcpp_lib
cspcpp_lib: $(cspcpp_lib)

.PHONY: cspcpp_test
cspcpp_test: $(cspcpp_test)

.PHONY: cspats_lib
cspats_lib: $(cspats_lib)

.PHONY: logtool_lib
logtool_lib: $(logtool_lib)

.PHONY: clean
clean:
	$(RM) $(objects) \
        $(programs) \
        $(libraries) \
        $(lib_test) \
        $(dependencies) \
        $(ats_c_files)

ifneq "$(MAKECMDGOALS)" "clean"
  include $(dependencies)
endif

# = rules ========================================
#
# %_sats.c: %.sats
$(sats_c_files): $(call atscname,%.sats): %.sats
	$(ATSOPT) --output $@ $(ATSCCFLAGS) --static $<; \
	if [ $$? -ne 0 ]; then \
          $(RM) $@; \
          rm $$$$.hack; \
        fi

# %_dats.c: %.dats
$(dats_c_files): $(call atscname,%.dats): %.dats
	$(ATSOPT) --output $@ $(ATSCCFLAGS) --dynamic $<; \
	if [ $$? -ne 0 ]; then \
          $(RM) $@; \
          rm $$$$.hack; \
        fi

#=========================


# xxx.depats: xxx.sats
$(sats_dep): %.$(depats): %.sats
	$(ATSOPT) $(ATSCCFLAGS) -dep1 -s $< | \
	$(SED) 's,\($(notdir $*)\.o\)[ :]*,$(dir $@)\1 $@: ,g' > $@.tmp
	$(MV) $@.tmp $@

# xxx.depats: xxx.sats
$(dats_dep): %.$(depats): %.dats
	$(ATSOPT) $(ATSCCFLAGS) -dep1 -d $< | \
	$(SED) 's,\($(notdir $*)\.o\)[ :]*,$(dir $@)\1 $@: ,g' > $@.tmp
	$(MV) $@.tmp $@

#=========================

# xxx.depgcc: xxx.cpp
$(cxx_dep): %.$(depgcc): %.cpp
	$(CXX) $(CFLAGS) $(CPPFLAGS) -M $< | \
	$(SED) 's,\($(notdir $*)\.o\)[ :]*,$(dir $@)\1 $@: ,g' > $@.tmp
	$(MV) $@.tmp $@

# xxx.depgcc: xxx.c
$(c_dep) : %.$(depgcc): %.c
	$(CC) $(CFLAGS) $(CPPFLAGS) -M $< | \
	$(SED) 's,\($(notdir $*)\.o\)[ :]*,$(dir $@)\1 $@: ,g' > $@.tmp
	$(MV) $@.tmp $@

# xxx.depgcc: xxx.c
$(sats_c_dep) $(dats_c_dep): %.$(depgcc): %.c
	$(CC) $(CFLAGS) $(CPPFLAGS) $(ATS_CC_INC) -M $< | \
	$(SED) 's,\($(notdir $*)\.o\)[ :]*,$(dir $@)\1 $@: ,g' > $@.tmp
	$(MV) $@.tmp $@

#=========================

# xxx_sats.o: xxx_sats.c
# xxx_dats.o: xxx_dats.c
#
$(ats_obj_files): %.o: %.c
	$(COMPILE.c) $(ATS_CC_INC) $(OUTPUT_OPTION) $<



#=========================
##########################################################
#    
#    
#    #LIBPARCOMB=$(ATSHOME)/contrib/parcomb/atsctrb_parcomb.o
#    LIBCSP := \
#    contrib/cspats/LIB/cspats_lib.o \
#    contrib/cspats/LIB/cspats.o \
#    contrib/cspats/LIB/common/ec.o \
#    contrib/cspats/LIB/common/logf.o \
#    contrib/cspats/LIB/common/syserr.o \
#    
#    ######
#    
#    #
#    # HX: Please uncomment the one you want, or skip it entirely
#    #
#    # ATSCCFLAGS=-D_ATS_GCATS
#    #
#    # '-flto' enables link-time optimization such as inlining lib functions
#    #
#    #ATSCCFLAGS=-O2 -flto -D_ATS_GCATS
#    
#    ######
#    
#    ######
#    RMF = rm -f
#    
#    # convert the file name to .o files
#    # $(call atsobjname,filelist)
#    define atsobjname
#    $(patsubst %.dats,%_dats.o,$(patsubst %.sats,%_sats.o,$1))
#    endef
#    
#    define atsdepname
#    $(patsubst %.dats,%_dats.d,$(patsubst %.sats,%_sats.d,$1))
#    endef
#    
#    define atshtmlname
#    $(patsubst %.dats,%_dats.html,$(patsubst %.sats,%_sats.html,$1))
#    endef
#    
#    SOURCES := \
#      test.dats \
#      contrib/cspats/SATS/cspats.sats \
#      contrib/cspats/DATS/cspats.dats \
#    
#    OBJECTS := $(call atsobjname,$(SOURCES))
#    
#    target := tester
#    
#    .PHONY: all
#    all: $(target)
#    
#    tester: $(OBJECTS)
#    	$(ATSCC) -o $@ $^ $(LIBCSP) -pthread -lstdc++
#    
#    
#    # #################
#    $(call atsobjname,%.sats): %.sats
#    	$(ATSCC) $(ATSCCFLAGS) -c $< -o $@
#    # || touch $@
#    
#    $(call atsobjname,%.dats): %.dats
#    	$(ATSCC) $(ATSCCFLAGS) -c $< -o $@
#    
#    #                  # #################
#    #                  # Generate dependency files
#    #                  # SOURCESsta := $(filter %.sats, $(SOURCES))
#    #                  # SOURCESdyn := $(filter %.dats, $(SOURCES))
#    #                  
#    #                  ifneq "$(findstring clean,$(MAKECMDGOALS))" "clean"
#    #                    ifneq "$(MAKECMDGOALS)" "html"
#    #                      -include $(call atsdepname,$(SOURCES))
#    #                    endif
#    #                  endif
#    
#    $(call atsdepname,%.sats): %.sats
#    	$(ATSOPT) -o $@.$$$$ -dep1 -s $<;    \
#    	sed 's/\(.*\)\.o[ :]*/\1.o $@ : /g' < $@.$$$$ > $@;    \
#    	rm -f $@.$$$$
#    
#    $(call atsdepname,%.dats): %.dats
#    	$(ATSOPT) -o $@.$$$$ -dep1 -d $<;    \
#    	sed 's/\(.*\)\.o[ :]*/\1.o $@ : /g' < $@.$$$$ > $@;    \
#    	rm -f $@.$$$$
#    ######
#    # Generate html files for ATS source code
#    source_sats := $(wildcard *.sats)
#    source_dats := $(wildcard *.dats)
#    
#    html_file_sats := $(call atshtmlname,$(source_sats))
#    html_file_dats := $(call atshtmlname,$(source_dats))
#    
#    .PHONY: html
#    
#    html: $(html_file_sats) $(html_file_dats)
#    
#    $(html_file_sats): $(call atshtmlname,%.sats): %.sats
#    	$(ATSOPT) --posmark_html -s $< > $@
#    
#    $(html_file_dats): $(call atshtmlname,%.dats): %.dats
#    	$(ATSOPT) --posmark_html -d $< > $@
#    
#    ######
#    
#    .PHONY: clean distclean
#    
#    clean::
#    	$(RMF) *~
#    	$(RMF) $(call atsobjname,*.sats *.dats)
#    	$(RMF) $(call atsdepname,*.sats *.dats)
#    	$(RMF) *_?ats.c
#    	$(RMF) $(target)
#    
#    distclean: clean
#    	$(RMF) $(call atshtmlname,*.sats *.dats)
#    
#    ###### end of [Makefile] ######
#    
#    
#    
